name: generate_2023-07_Pilot-ER
on:
  push:
    branches:
    - main
    
#  schedule:
#    - cron:  '1 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: metanorma/metanorma:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout other repo
        uses: actions/checkout@v3       # checkout the repository content to github runner
        with:
          repository: gbuehler/climate-resilience-dwg
          path: 2023-07_Pilot-ER
      - name: Generate document
        run: |
          cd 2023-07_Pilot-ER
          pwd
          cd 2023-07_Pilot-ER
          # mkdir target                  # Metanorma output will be there.
          # Generate HTML only because the deltas are efficiently handled by versionning systems, contrarily to PDF binary.
          
          metanorma compile  -t ogc -x  xml,html,pdf --agree-to-terms document.adoc
           
          mv document.html 23-016.html
          mv document.pdf 23-016.pdf
        
          git config --global user.name 'gbuehler'
          git config --global user.email 'gbuehler@ogc.org'
          git add .
          git commit --message "Automated generation of HTML document"
          git push
